### ISSUE TITLE
Implement FIleProvider in hard coded template

### ISSUE THREAD

**Issue by ThomasCWright** [ThomasCWright/Sudoku#13]
Used https://stackoverflow.com/q/38983649/7312441 as starting point, however, following error thrown

>
11-23 12:09:14.323 23238  5039 I python  :  jnius.jnius.JavaException: JVM exception occurred: file:///./blank_9x9.png exposed beyond app through ClipData.Item.getUri() 
>
Quick search reveals promising post https://github.com/kivy/plyer/issues/500#issuecomment-504856851

also:
https://github.com/alecvn/kivy-android-camera#kivy-example-for-android-camera

but will create a new issue for this if next try can't make tests.  Passed tests but still too big a rabbithole for task in hand.  Off to backlog

_Originally posted by @ThomasCWright in https://github.com/ThomasCWright/Sudoku/issues/1#issuecomment-732094471_

**Comment by ThomasCWright** [comment]
Due to the differing nature of print services on Android, the MVP needs to be able to fully share an image file via the app's FIleProvider.

On success, issue #12 should be looked at for completion.

**Comment by ThomasCWright** [comment]
Update `C:\Users\tcw25\Documents\GitHub\Sudoku\.buildozer\android\platform\build-arm64-v8a\build\bootstrap_builds\sdl2\templates\AndroidManifest.tmpl.xml`

**Comment by ThomasCWright** [comment]
Implementing:
https://github.com/kivy/python-for-android/issues/2020#issuecomment-735021748

Looks like a great solution for future use of `androidx` but because 
> This requires android.api=28 or greater

No good for developing for Dad who's on api=25

**Comment by ThomasCWright** [comment]
OK.  Back to the following [link](https://github.com/kivy/plyer/issues/500#issuecomment-504856851)

**Comment by ThomasCWright** [comment]
Adding to main.py:

```
FileProvider = autoclass('android.support.v4.content.FileProvider')
Context = autoclass("android.content.Context")
Environment = autoclass("android.os.Environment")
```

**Comment by ThomasCWright** [comment]
`support-v4-24.1.1.aar` is required:
Downloaded here: https://maven.google.com/web/index.html?#com.android.support:support-v4:24.1.1
Added to `buildozer.spec`:
```
# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
android.add_aars = support-v4-24.1.1.aar
```

**Comment by ThomasCWright** [comment]
Now modify existing share function to take advantage of FileProvider class:
> photoUri = FileProvider.getUriForFile(
            Context.getApplicationContext(),
            "org.test.myapp.fileprovider",
            photoFile
        )

**Comment by ThomasCWright** [comment]
Trying forked `p4a:develop` with changes according to:
https://github.com/alecvn/kivy-android-camera#kivy-example-for-android-camera
`$ pip install -e .`
`$ buildozer android debug` => gives correct target API==29 but no change in AndroidManifest.xml
=> `buildozer appclean` and repeat step above

**Comment by ThomasCWright** [comment]
Deleting fork of p4a and cloning https://github.com/pavelsof/python-for-android.git instead

From https://github.com/kivy/python-for-android/pull/2200#issuecomment-734983761

Insert 
``` 
   <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="{{ args.package }}.fileprovider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_paths" />
    </provider>
```
into AndroidManifest.tml.xml

**Comment by ThomasCWright** [comment]
Reverting to https://github.com/Fak3/python-for-android.git and following [comment](https://github.com/kivy/python-for-android/pull/1922#issue-297535738)

`conda install -c anaconda python=3.7`

**Comment by ThomasCWright** [comment]
Giving up on Fak3 PR and reverting to stock buildozer to try my luck with some hard wiring

**Comment by ThomasCWright** [comment]
Following this [comment](https://github.com/kivy/plyer/issues/500#issuecomment-565532048)

- `buildozer android debug`
- Add path to FileProvider lib:
    `android.add_aars = ./support-v4-24.1.1.aar`
- `.buildozer/android/platform/build-arm64-v8a/dists/BVWSudoku__arm64-v8a/templates/AndroidManifest.tmpl.xml` updated
- Then create a folder named xml in the `.buildozer/android/platform/build-arm64-v8a/dists/BVWSudoku__arm64-v8a/build\src\main\res` directory and create a file named `file_paths.xml` 
- `buildozer android debug`

**Comment by ThomasCWright** [comment]
Transferred to Ubuntu laptop

**Comment by ThomasCWright** [comment]
:champagne: :champagne: :champagne: :champagne: 
modify `/home/tcw/Github/Sudoku/.buildozer/android/platform/build-arm64-v8a/dists/BVWSudoku__arm64-v8a/templates/AndroidManifest.tmpl.xml` gives file provider in manifest

**Comment by ThomasCWright** [comment]
Error: createNewFile permission denied in logcat
Add `android:requestLegacyExternalStorage="true"` to application tag
```    
<application android:label="@string/app_name"
                 {% if debug %}android:debuggable="true"{% endif %}
                 android:icon="@drawable/icon"
                 android:allowBackup="{{ args.allow_backup }}"
                 android:theme="{{args.android_apptheme}}{% if not args.window %}.Fullscreen{% endif %}"
                 android:hardwareAccelerated="true"
                 android:requestLegacyExternalStorage="true" >
```
[kudos](https://stackoverflow.com/a/63596380/7312441)

**Comment by ThomasCWright** [comment]
#17

**Comment by t0theRANCH** [comment]
I got tired of doing this repeatedly, so I wrote a nice little script to automate it
[https://github.com/t0theRANCH/addFileProvider](url)
